/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "and_gate_synth.v:1" *)
module and_gate_synth(a, b, y);
  (* src = "and_gate_synth.v:2" *)
  input a;
  (* src = "and_gate_synth.v:2" *)
  input b;
  (* src = "and_gate_synth.v:3" *)
  output y;
  AND2X1 _0_ (
    .A(a),
    .B(b),
    .Y(y)
  );
endmodule
